---
- name: Update apt cache
  apt:
    update_cache: true
  when: ansible_os_family == 'Debian'

- name: Install WireGuard
  package:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - "iproute{% if ansible_os_family == 'Debian' %}2{% endif %}"
      - wireguard-tools
      - qrencode
      - git
